version: '3.2'
services:

  yum:
    container_name: senzing-yum
    environment:
      SENZING_ACCEPT_EULA: "${SENZING_ACCEPT_EULA}"
    image: senzing/yum:1.1.0
    networks:
      - backend
    restart: on-failure
    user: "0"
    volumes:
      - ${SENZING_DATA_DIR}:/opt/senzing/data
      - ${SENZING_ETC_DIR}:/etc/opt/senzing
      - ${SENZING_G2_DIR}:/opt/senzing/g2
      - ${SENZING_VAR_DIR}:/var/opt/senzing
  
networks:
  backend:
