SENZING_ACCEPT_EULA: false

SENZING_DATA_DIR: ~/senzing-docker-app-demo/senzing/data
SENZING_ETC_DIR:  ~/senzing-docker-app-demo/senzing/etc
SENZING_G2_DIR:   ~/senzing-docker-app-demo/senzing/g2
SENZING_VAR_DIR:  ~/senzing-docker-app-demo/senzing/var
