JUPYTER_NOTEBOOKS_SHARED_DIR: ~/senzing-docker-app-demo/jupyter
POSTGRES_DB: G2
POSTGRES_DIR: ~/senzing-docker-app-demo/pgsql/data
POSTGRES_PASSWORD: postgres
POSTGRES_USERNAME: postgres
RABBITMQ_DIR: ~/senzing-docker-app-demo/rabbitmq
RABBITMQ_PASSWORD: bitnami
RABBITMQ_USERNAME: user
SENZING_DATA_DIR: ~/senzing-docker-app-demo/data
SENZING_DATA_VERSION_DIR: ~/senzing-docker-app-demo/data/1.0.0
SENZING_DATA_SOURCE: TEST
SENZING_ENTITY_TYPE: TEST
SENZING_ETC_DIR:  ~/senzing-docker-app-demo/etc
SENZING_G2_DIR:   ~/senzing-docker-app-demo/g2
SENZING_INPUT_URL: "https://s3.amazonaws.com/public-read-access/TestDataSets/loadtest-dataset-1M.json"
SENZING_MONITORING_PERIOD_IN_SECONDS: 600
SENZING_PROCESSES: 1
SENZING_THREADS_PER_PROCESS: 1
SENZING_VAR_DIR:  ~/senzing-docker-app-demo/var


