POSTGRES_DB: G2
POSTGRES_DIR: /var/lib/pgsql/data
POSTGRES_PASSWORD: postgres
POSTGRES_USERNAME: postgres
RABBITMQ_DIR: /var/lib/rabbitmq
RABBITMQ_PASSWORD: bitnami
RABBITMQ_USERNAME: user
SENZING_ACCEPT_EULA: false
SENZING_DATA_DIR: /opt/senzing/data
SENZING_DATA_SOURCE: TEST
SENZING_ENTITY_TYPE: TEST
SENZING_ETC_DIR: /etc/opt/senzing
SENZING_G2_DIR: /opt/senzing/g2
SENZING_INPUT_URL: "https://s3.amazonaws.com/public-read-access/TestDataSets/loadtest-dataset-1M.json"
SENZING_MONITORING_PERIOD_IN_SECONDS: 600
SENZING_PROCESSES: 1
SENZING_THREADS_PER_PROCESS: 1
SENZING_VAR_DIR: /var/opt/senzing
